INSERT INTO map (id, title, description, map_path, sources)
VALUES
(1,'Carte générale du Japon, 1978','','../../cartes/japon_yagani.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(2,'Growth of official cities 1935-1940','Department of State, Map Division États-Unis, 1947','../../cartes/Growth_of_official_cities_1935-1940.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(3,'Japan sex ratios, 1940','Department of State, Map Division États-Unis','../../cartes/Japan_sex_ratios_1940.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(4,'Plan de la ville de Tours aux diverses époques de son Histoire','Dressé Par le Dr Eugène Giraudet en 1872','../../cartes/Tours.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(5,'Plan de Nagasaki, 1821','','../../cartes/Nagasaki_Tomijimaya.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(6,'Grand incendie d\'Edo de 1855, 19ème siècle','','../../cartes/Grand_incendie_Edo.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(7,'Royaume du Japon par P. Ph. Briet, 1668','','../../cartes/Royaume_du_Japon.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(8,'Carte des Amériques, 1570','titre original:"Americae sive novi orbis nova descriptio"','../../cartes/ameriques_1570.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(9,'Carte ecclésiastique des Etats-Unis d\'Amérique, 1877','','../../cartes/Carte_ecclesiastique_des_Etats-Unis_d_Amerique.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(10,'Afrique, Chemins de fer et Navigation à vapeur, 1904','','../../cartes/Afrique_Chemins.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(11,'Taux de natalité et âge moyen de la mère à la naissance en 2020, et nombre de naissances en 2019','','../../cartes/Taux_de_natalite2019.png','Insee, État civil, Estimations de population'),
(12,'Part des diplômés d\'un BAC+2 dans la pop. non scolarisée de 15 ans ou + en 2017','','../../cartes/Part_des_diplomes_2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(13,'Part des maisons dans le nombre total de logements en 2017','','../../cartes/Part_des_maisons2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(14,'Écart salaire net horaire moyen des femmes par rapport aux hommes selon la catégorie socioprofessionnelle en 2018','','../../cartes/ecart_salaire_2018.png','Insee, Bases Tous salariés'),
(15,'Taux d\'artificialisation des sols, 2018 ','','../../cartes/Taux_d_artificialisation.png','Union européenne - Ministère de la transition écologique - CORINE Land Cover'),
(16,'Part des surfaces en agriculture biologique, 2019','','../../cartes/surfaces_agriculture_2019.png','Ministère en charge de l\'agriculture, Service de la statistique et de la prospective (SSP), Agreste, Statistique agricole annuelle, Agence Bio'),
(17,'Part des ménages ayant au moins 1 voiture, 2017','','../../cartes/voiture_2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(18,'Réseau de proximité pôle emploi et réseau partenarial pôle emploi 2019','','../../cartes/pole_emploi_2019.png','Insee, Base permanente des équipements (Bpe)'),
(19,'Salaire net horaire moyen en 2018','','../../cartes/Salaire_net_horaire2018.png','Insee, Bases Tous salariés'),
(20,'Part des emplois salariés dans le nombre d’emplois au lieu de travail en 2017','','../../cartes/Part_des_emplois_salaries.png','Insee, Recensement de la population (RP), exploitation principale'),
(21,'Part des logements vacants dans le nombre total de logements en 2017','','../../cartes/logement_vacant2017.png','Insee, séries historiques du RP, exploitation principale'),
(22,'Part des diplômés d\'un BAC+5 ou plus dans la pop. non scolarisée de 15 ans ou + 2017','','../../cartes/Part_diplome_bac5.png','Insee, Recensement de la population (RP), exploitation principale'),
(23,'Évolution annuelle moyenne de la population 2013-2018','','../../cartes/population_2013_2018.png',' Insee, Recensements de la population (RP)'),
(24,'Part des personnes âgées moins de 15 ans dans la population en 2017','','../../cartes/pers_moins_15ans_2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(25,'Part des personnes âgées de 25 à 64 ans dans la population en 2017','','../../cartes/25_64ans_2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(26,'Part des personnes âgées de 80 ans ou plus en 2017','','../../cartes/pers_agee_2017.png','Insee, Recensement de la population (RP), exploitation principale'),
(27,'Taille moyenne des ménages en 2017','','../../cartes/Taille_moyenne_des_menages2017.png','Insee, séries historiques du RP, exploitation principale'),
(28,'Densité de population, 1876','','../../cartes/Densite_1876.png','Insee, séries historiques du RP, exploitation principale'),
(29,'Densité de population, 1975','','../../cartes/Densite_1975.png','Insee, séries historiques du RP, exploitation principale'),
(30,'Cosmographia, carte du monde au 15ème siècle','Par Claudius Ptolomaeus 1450-1471','../../cartes/Cosmographia.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(31,'Carte de l\'Océan Atlantique nord-est, 16ème siècle','','../../cartes/atlantique_nord.jpg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(32,'Chemin de fer Paris-Cologne-Strasbourg, 1852','','../../cartes/chemin_fer.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(33,'Carte de l\'Europe en 1556','Carte scolaire de 1821','../../cartes/Carte_de_l_Europe_en_1556.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(34,'Carte de l\'empire de Charlemagne après le partage de 806','Carte scolaire de 1876','../../cartes/charlemagne.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(35,'Comic map of the seat of war with entirely new features','Carte humouristique de 1854','../../cartes/comic_map_1854.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(36,'Nouvelle France, Nouvelle Angleterre, Acadie, 16ème siècle','','../../cartes/Nouvelle_France.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(37,'Galliae regni potentiss. nova descriptio','Carte de France, 1570','../../cartes/Galliae_regni_potentiss_nova descriptio.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(38,'Carte de Belgique et des Pays-Bas, 1570','titre original: Descriptio Germaniae inferioris','../../cartes/Descriptio_Germaniae_inferioris.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France'),
(39,'Carte nautique des côtes du Canada','16ème siècle','../../cartes/canada_st_laurent.jpeg','Source gallica.bnf.fr  Bibliothèque nationale de France');


INSERT INTO map (id, title, description, map_path, sources)
VALUES
(40,'Les migrations humaines','Les chiffres sont en milliers d\'années. Les vagues de migartions dont identifiées grace à l\'ADN mitochondriale','../../migrations_humaines.png','Wikipedia Commons,User:Bilderbot,CC BY-SA 3.0'),
(41,'Peuplement de la Micronésie',,'../../peuplement_micronesie.png','Christophe Cagé, GNU Free Documentation License'),
(42,'Zone d\'extension du biface','En marron: zones ou l\'on a retrouvé silex taillés sur deux faces (bi-face)','../../Biface_Extension.png','Auteur: José Manuel Benito Álvarez, Public Domain'),
(43,'Carte de la couleur de cheveux dominante',,'../../hair_color.png','Dark Tichondrias, GNU Free Documentation License'),
(44,'Ou est cultivé l\'huile d\'olive en Europe ?',,'../../olive.jpg','Auteur: VPC, GNU Free Documentation License'),
(45,'Europe Agricultural révolution','diffusion de l\'agriculture en Europe','../../europe_agricultural_revolution.gif','Wikirictor, CC BY-SA 4.0'),
(46,'Ou sont produites les cerises ?',,'../../cerise_2016.png','JackintheBox, CC BY-SA 4.0'),
(47,'Ou et quand a été inventée l\'agriculture?',,'../../invention_agri.png','Darius,CC0 1.0 Universal'),
(48,'Qui sont les plus gros producteurs de pomme de terre ?',,'../../patate2016.png','JackintheBox, CC BY-SA 4.0'),
(49,'Qui sont les plus gros producteurs d\'artichaut ?',,'../../artichaut2016.png','JackintheBox, CC BY-SA 4.0'),
(50,'Projection de l\'impact de changement climatique sur la production agricole',,'../../agri_chang_clim.png','European Environment Agency, Copenhagen, Denmark'),
(51,'Le mot \'thé\' en Europe',,'../../mot_the_europe.png','Poulpy, CC BY-SA 3.0'),
(52,'Top 20 des consomateurs de thé dans le monde',,'../../conso_the.png','Ncrump11, CC BY-SA 4.0'),
(53,'Carte des cables sous-marins',,'../../submarine_cable.png','OpenStreetMap contributors, CC-BY-SA 2.0'),
(54,'Reseau social le plus populaire par pay en 2014',,'../../reseau_soc.jpg','Jirka.h23, CC BY-SA 4.0'),
(55,'Ridleyville','Plan du Los Angeles du futur construit pour les scène extérieures de Blade Runner (Ridley Scott, 1982),fan made.','../../blade.png','David Luque,Luis Argerich, CC BY-SA 2.0'),
(56,'',,'',''),
(57,'',,'',''),
(58,'',,'',''),
(59,'',,'',''),
(60,'',,'',''),
(61,'',,'',''),
(62,'',,'',''),
(63,'',,'',''),
(64,'',,'',''),
(65,'',,'','');
